In [25]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [26]:
import os
import cv2
import tensorflow as tf
import pandas as pd
import numpy as np


In [27]:
# Load the datasets
train_annotations1 = pd.read_csv('/content/Licplatesdetection_train.csv')
train_images1 = []
for img_id in train_annotations1['img_id']:
    img = cv2.imread(f'/content/drive/MyDrive/license_plates_detection_train/{img_id}')
    img = cv2.resize(img, (255, 255))
    train_images1.append(img)

In [28]:
train_annotations2 = pd.read_csv('/content/Licplatesrecognition_train.csv')
train_images2 = []
for img_id in train_annotations2['img_id']:
    img = cv2.imread(f'/content/drive/MyDrive/license_plates_recognition_train/{img_id}')
    img = cv2.resize(img, (255, 255))
    train_images2.append(img)



In [29]:

test_images = []
for i in os.listdir('/content/drive/MyDrive/test/test/'):
    img = cv2.imread(os.path.join('/content/drive/MyDrive/test/test/',i))
    img = cv2.resize(img, (255, 255))
    test_images.append(img)

In [30]:
train_images1 = np.array(train_images1) / 255.0

In [31]:
train_images2 = np.array(train_images2) / 255.0

In [32]:
test_images = np.array(test_images) / 255.0

In [33]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

In [34]:
# Define the license plate detection model
def detection_model():
    model = tf.keras.models.Sequential([
        Conv2D(32, (3, 3), activation='relu', input_shape=(255, 255, 3)),
        MaxPooling2D((2, 2)),
        Conv2D(64, (3, 3), activation='relu'),
        MaxPooling2D((2, 2)),
        Conv2D(128, (3, 3), activation='relu'),
        MaxPooling2D((2, 2)),
        Flatten(),
        Dense(128, activation='relu'),
        Dense(4, activation='linear')
    ])
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

# Define the character recognition model
def recognition_model(input_shape):
    model = tf.keras.models.Sequential([
        Conv2D(32, (3, 3), activation='relu', input_shape=input_shape),
        MaxPooling2D((2, 2)),
        Conv2D(64, (3, 3), activation='relu'),
        MaxPooling2D((2, 2)),
        Conv2D(128, (3, 3), activation='relu'),
        MaxPooling2D((2, 2)),
        Flatten(),
        Dense(128, activation='relu'),
        Dense(36, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model



In [35]:
# Train the license plate detection model
detection_model = detection_model()
detection_model.fit(train_images1, train_annotations1[['ymin', 'xmin', 'ymax', 'xmax']].values, epochs=10, batch_size=32)



Epoch 1/10
29/29 [==============================] - 4s 67ms/step - loss: 30199.4395
Epoch 2/10
29/29 [==============================] - 2s 64ms/step - loss: 14392.6582
Epoch 3/10
29/29 [==============================] - 2s 65ms/step - loss: 14002.7715
Epoch 4/10
29/29 [==============================] - 2s 64ms/step - loss: 12827.3770
Epoch 5/10
29/29 [==============================] - 2s 66ms/step - loss: 12243.2871
Epoch 6/10
29/29 [==============================] - 2s 69ms/step - loss: 10243.1797
Epoch 7/10
29/29 [==============================] - 2s 68ms/step - loss: 9145.5430
Epoch 8/10
29/29 [==============================] - 2s 65ms/step - loss: 7916.1606
Epoch 9/10
29/29 [==============================] - 2s 65ms/step - loss: 7255.5815
Epoch 10/10
29/29 [==============================] - 2s 65ms/step - loss: 6542.8066


In [36]:

# Define the character recognition model

model = tf.keras.models.Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(255,255,3)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(36, activation='softmax')
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [37]:
model

In [38]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_15 (Conv2D)          (None, 253, 253, 32)      896       
                                                                 
 max_pooling2d_15 (MaxPooli  (None, 126, 126, 32)      0         
 ng2D)                                                           
                                                                 
 conv2d_16 (Conv2D)          (None, 124, 124, 64)      18496     
                                                                 
 max_pooling2d_16 (MaxPooli  (None, 62, 62, 64)        0         
 ng2D)                                                           
                                                                 
 conv2d_17 (Conv2D)          (None, 60, 60, 128)       73856     
                                                                 
 max_pooling2d_17 (MaxPooli  (None, 30, 30, 128)      

In [39]:

train_images2

array([[[[0.39215686, 0.38431373, 0.34117647],
         [0.38823529, 0.38039216, 0.3372549 ],
         [0.36078431, 0.35294118, 0.30980392],
         ...,
         [0.65490196, 0.6627451 , 0.60392157],
         [0.65490196, 0.66666667, 0.60784314],
         [0.65490196, 0.66666667, 0.60784314]],

        [[0.39215686, 0.38431373, 0.34117647],
         [0.38823529, 0.38039216, 0.3372549 ],
         [0.36078431, 0.35294118, 0.30980392],
         ...,
         [0.65098039, 0.66666667, 0.60392157],
         [0.65490196, 0.66666667, 0.60784314],
         [0.65490196, 0.66666667, 0.60784314]],

        [[0.39215686, 0.38431373, 0.34117647],
         [0.38823529, 0.38039216, 0.3372549 ],
         [0.36078431, 0.35294118, 0.30980392],
         ...,
         [0.65490196, 0.66666667, 0.60392157],
         [0.65490196, 0.66666667, 0.60784314],
         [0.65490196, 0.66666667, 0.60784314]],

        ...,

        [[0.18823529, 0.19607843, 0.17254902],
         [0.18823529, 0.19607843, 0.17254902]

In [40]:
train_annotations2 = train_annotations2['text']

In [41]:
list(train_annotations2)

['117T3989',
 '128T8086',
 '94T3458',
 '133T6719',
 '68T5979',
 '106T2131',
 '117T2600',
 '58T8888',
 '93T5599',
 '155T1216',
 '191T2827',
 '127T9733',
 '121T237',
 '96T8557',
 '172T9314',
 '152T8269',
 '127T9295',
 '188T956',
 '179T7121',
 '169T9685',
 '161T3230',
 '74T3819',
 '155T5259',
 '137T5115',
 '156T2325',
 '169T9685',
 '134T3970',
 '120T5039',
 '121T6559',
 '145T5368',
 '100T8109',
 '118T5018',
 '68T3759',
 '190T413',
 '125T5378',
 '182T2759',
 '165T6025',
 '119T9133',
 '66T5697',
 '109T2328',
 '84T1104',
 '165T895',
 '114T7304',
 '37T3819',
 '115T6064',
 '98T5178',
 '85T3827',
 '112T6988',
 '68T6341',
 '90T4636',
 '141T13',
 '181T7519',
 '106T9514',
 '156T3853',
 '159T7948',
 '155T9278',
 '191T9338',
 '164T9653',
 '148T2903',
 '90T9848',
 '87T9170',
 '176T755',
 '156T7524',
 '168T1951',
 '31T8115',
 '193T4091',
 '142T8217',
 '159T3782',
 '173T4951',
 '136T2146',
 '161T3015',
 '194T735',
 '123T3112',
 '112T8576',
 '70T652',
 '140T566',
 '89T3511',
 '40T1901',
 '195T2612',
 '8

In [42]:
char_dict = {str(i): char for i, char in enumerate('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ')}
print(char_dict)

{'0': '0', '1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8', '9': '9', '10': 'A', '11': 'B', '12': 'C', '13': 'D', '14': 'E', '15': 'F', '16': 'G', '17': 'H', '18': 'I', '19': 'J', '20': 'K', '21': 'L', '22': 'M', '23': 'N', '24': 'O', '25': 'P', '26': 'Q', '27': 'R', '28': 'S', '29': 'T', '30': 'U', '31': 'V', '32': 'W', '33': 'X', '34': 'Y', '35': 'Z'}


In [43]:
char_final = {char:str(i) for i, char in enumerate('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ')}
print(char_final)

{'0': '0', '1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8', '9': '9', 'A': '10', 'B': '11', 'C': '12', 'D': '13', 'E': '14', 'F': '15', 'G': '16', 'H': '17', 'I': '18', 'J': '19', 'K': '20', 'L': '21', 'M': '22', 'N': '23', 'O': '24', 'P': '25', 'Q': '26', 'R': '27', 'S': '28', 'T': '29', 'U': '30', 'V': '31', 'W': '32', 'X': '33', 'Y': '34', 'Z': '35'}


In [44]:
train_annotations2=list(train_annotations2)
print(train_annotations2)

['117T3989', '128T8086', '94T3458', '133T6719', '68T5979', '106T2131', '117T2600', '58T8888', '93T5599', '155T1216', '191T2827', '127T9733', '121T237', '96T8557', '172T9314', '152T8269', '127T9295', '188T956', '179T7121', '169T9685', '161T3230', '74T3819', '155T5259', '137T5115', '156T2325', '169T9685', '134T3970', '120T5039', '121T6559', '145T5368', '100T8109', '118T5018', '68T3759', '190T413', '125T5378', '182T2759', '165T6025', '119T9133', '66T5697', '109T2328', '84T1104', '165T895', '114T7304', '37T3819', '115T6064', '98T5178', '85T3827', '112T6988', '68T6341', '90T4636', '141T13', '181T7519', '106T9514', '156T3853', '159T7948', '155T9278', '191T9338', '164T9653', '148T2903', '90T9848', '87T9170', '176T755', '156T7524', '168T1951', '31T8115', '193T4091', '142T8217', '159T3782', '173T4951', '136T2146', '161T3015', '194T735', '123T3112', '112T8576', '70T652', '140T566', '89T3511', '40T1901', '195T2612', '83T1812', '181T2562', '70T652', '118T6637', '194T558', '175T7944', '133T6719', '

In [45]:
train_annotations2_char=[]
for i in train_annotations2:
  s=[]
  for j in i:
    s.append(int(char_final[j]))
  train_annotations2_char.append(s)
  s=[]


In [46]:
print(train_annotations2_char)


[[1, 1, 7, 29, 3, 9, 8, 9], [1, 2, 8, 29, 8, 0, 8, 6], [9, 4, 29, 3, 4, 5, 8], [1, 3, 3, 29, 6, 7, 1, 9], [6, 8, 29, 5, 9, 7, 9], [1, 0, 6, 29, 2, 1, 3, 1], [1, 1, 7, 29, 2, 6, 0, 0], [5, 8, 29, 8, 8, 8, 8], [9, 3, 29, 5, 5, 9, 9], [1, 5, 5, 29, 1, 2, 1, 6], [1, 9, 1, 29, 2, 8, 2, 7], [1, 2, 7, 29, 9, 7, 3, 3], [1, 2, 1, 29, 2, 3, 7], [9, 6, 29, 8, 5, 5, 7], [1, 7, 2, 29, 9, 3, 1, 4], [1, 5, 2, 29, 8, 2, 6, 9], [1, 2, 7, 29, 9, 2, 9, 5], [1, 8, 8, 29, 9, 5, 6], [1, 7, 9, 29, 7, 1, 2, 1], [1, 6, 9, 29, 9, 6, 8, 5], [1, 6, 1, 29, 3, 2, 3, 0], [7, 4, 29, 3, 8, 1, 9], [1, 5, 5, 29, 5, 2, 5, 9], [1, 3, 7, 29, 5, 1, 1, 5], [1, 5, 6, 29, 2, 3, 2, 5], [1, 6, 9, 29, 9, 6, 8, 5], [1, 3, 4, 29, 3, 9, 7, 0], [1, 2, 0, 29, 5, 0, 3, 9], [1, 2, 1, 29, 6, 5, 5, 9], [1, 4, 5, 29, 5, 3, 6, 8], [1, 0, 0, 29, 8, 1, 0, 9], [1, 1, 8, 29, 5, 0, 1, 8], [6, 8, 29, 3, 7, 5, 9], [1, 9, 0, 29, 4, 1, 3], [1, 2, 5, 29, 5, 3, 7, 8], [1, 8, 2, 29, 2, 7, 5, 9], [1, 6, 5, 29, 6, 0, 2, 5], [1, 1, 9, 29, 9, 1, 3, 3], [6,

In [47]:
padded_annotations = tf.keras.preprocessing.sequence.pad_sequences(train_annotations2_char, padding='post', value=0)

print(padded_annotations)

[[ 1  1  7 ...  9  8  9]
 [ 1  2  8 ...  0  8  6]
 [ 9  4 29 ...  5  8  0]
 ...
 [ 1  8  0 ...  0  6  0]
 [ 8  7 29 ...  6  9  0]
 [ 1  5  9 ...  8  9  4]]


In [48]:
train_images2

array([[[[0.39215686, 0.38431373, 0.34117647],
         [0.38823529, 0.38039216, 0.3372549 ],
         [0.36078431, 0.35294118, 0.30980392],
         ...,
         [0.65490196, 0.6627451 , 0.60392157],
         [0.65490196, 0.66666667, 0.60784314],
         [0.65490196, 0.66666667, 0.60784314]],

        [[0.39215686, 0.38431373, 0.34117647],
         [0.38823529, 0.38039216, 0.3372549 ],
         [0.36078431, 0.35294118, 0.30980392],
         ...,
         [0.65098039, 0.66666667, 0.60392157],
         [0.65490196, 0.66666667, 0.60784314],
         [0.65490196, 0.66666667, 0.60784314]],

        [[0.39215686, 0.38431373, 0.34117647],
         [0.38823529, 0.38039216, 0.3372549 ],
         [0.36078431, 0.35294118, 0.30980392],
         ...,
         [0.65490196, 0.66666667, 0.60392157],
         [0.65490196, 0.66666667, 0.60784314],
         [0.65490196, 0.66666667, 0.60784314]],

        ...,

        [[0.18823529, 0.19607843, 0.17254902],
         [0.18823529, 0.19607843, 0.17254902]

In [49]:
padded_annotations=np.array(padded_annotations)

In [50]:
padded_annotations

array([[ 1,  1,  7, ...,  9,  8,  9],
       [ 1,  2,  8, ...,  0,  8,  6],
       [ 9,  4, 29, ...,  5,  8,  0],
       ...,
       [ 1,  8,  0, ...,  0,  6,  0],
       [ 8,  7, 29, ...,  6,  9,  0],
       [ 1,  5,  9, ...,  8,  9,  4]], dtype=int32)

In [51]:
tensor = tf.convert_to_tensor(padded_annotations)

In [62]:
image_tensor=tf.convert_to_tensor(train_images2)

In [63]:
# Creating TensorFlow Dataset from Tensors
dataset = tf.data.Dataset.from_tensor_slices((image_tensor,tensor ))


In [54]:
dataset

<_TensorSliceDataset element_spec=(TensorSpec(shape=(255, 255, 3), dtype=tf.float64, name=None), TensorSpec(shape=(8,), dtype=tf.int32, name=None))>

In [64]:
batched_dataset = dataset.batch(32)

In [66]:
batched_dataset

<_BatchDataset element_spec=(TensorSpec(shape=(None, 255, 255, 3), dtype=tf.float64, name=None), TensorSpec(shape=(None, 8), dtype=tf.int32, name=None))>

In [67]:
model = tf.keras.models.Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(255,255,3)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(36, activation='softmax')
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [69]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_18 (Conv2D)          (None, 253, 253, 32)      896       
                                                                 
 max_pooling2d_18 (MaxPooli  (None, 126, 126, 32)      0         
 ng2D)                                                           
                                                                 
 conv2d_19 (Conv2D)          (None, 124, 124, 64)      18496     
                                                                 
 max_pooling2d_19 (MaxPooli  (None, 62, 62, 64)        0         
 ng2D)                                                           
                                                                 
 conv2d_20 (Conv2D)          (None, 60, 60, 128)       73856     
                                                                 
 max_pooling2d_20 (MaxPooli  (None, 30, 30, 128)      

In [70]:
model.fit(batched_dataset,epochs=10, batch_size=32)

Epoch 1/10


InvalidArgumentError: Graph execution error:

Detected at node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits defined at (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main

  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code

  File "/usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py", line 37, in <module>

  File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 992, in launch_instance

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py", line 619, in start

  File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 195, in start

  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever

  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once

  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run

  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 685, in <lambda>

  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 738, in _run_callback

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 825, in inner

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 786, in run

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 361, in process_one

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 539, in execute_request

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py", line 302, in do_execute

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py", line 539, in run_cell

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code

  File "<ipython-input-70-26706becdf1e>", line 1, in <cell line: 1>

  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1807, in fit

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1401, in train_function

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1384, in step_function

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1373, in run_step

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1151, in train_step

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1209, in compute_loss

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/compile_utils.py", line 277, in __call__

  File "/usr/local/lib/python3.10/dist-packages/keras/src/losses.py", line 143, in __call__

  File "/usr/local/lib/python3.10/dist-packages/keras/src/losses.py", line 270, in call

  File "/usr/local/lib/python3.10/dist-packages/keras/src/losses.py", line 2454, in sparse_categorical_crossentropy

  File "/usr/local/lib/python3.10/dist-packages/keras/src/backend.py", line 5775, in sparse_categorical_crossentropy

logits and labels must have the same first dimension, got logits shape [32,36] and labels shape [256]
	 [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_7143]

In [ ]:
# Evaluate the models on the test set
test_predictions = []
for img in test_images:
    # Detect the license plate
    img = cv2.resize(img, (224, 224))
    img = np.expand_dims(img, axis=0)
    detection_output = detection_model.predict